# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_library:
  name: uploadcare
  config:
    publicKey: df19f57714627515ea61
    multiple: false
    tabs: "file camera url facebook gdrive"
    effects: "crop, rotate, enhance, grayscale"
    imageShrink: "2000x2000"
    previewStep: true
    clearable: true

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - {
              label: PageTitle,
              name: pageTitle,
              widget: hidden,
              default: Home Page,
            }
          - { label: Slug, name: slug, widget: hidden, default: "" }
          - label: "title section"
            name: "titleSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: subtitle, name: subtitle, widget: string }
              - label: "Button 1"
                name: "button1"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }
              - label: "Button 2"
                name: "button2"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }

          - label: "About Us Section"
            name: "aboutUsSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - {
                  label: short description,
                  name: shortDescription,
                  widget: string,
                }
              - { label: description, name: description, widget: string }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }
              - { label: Image, name: image, widget: image }
          - label: "How It Works Section"
            name: "howItWorksSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - {
                  label: short description,
                  name: shortDescription,
                  widget: string,
                }
              - { label: description, name: description, widget: string }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }
              - { label: Image, name: image, widget: image }
          - label: "Services Section"
            name: "servicesSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }
          - label: "Inline Banner"
            name: "inlineBanner"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }
              - { label: Background, name: background, widget: image }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }
          - label: "Case Studies Section"
            name: "caseStudiesSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }
          - label: "News Section"
            name: "newsSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }
          - label: "Certifications Section"
            name: "certificationsSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - {
                  label: short description,
                  name: shortDescription,
                  widget: string,
                }
              - { label: description, name: description, widget: string }
              - {
                  label: Logos,
                  name: logos,
                  widget: image,
                  options: { media_library: { config: { multiple: true } } },
                }
      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: HomePage,
            }
          - {
              label: PageTitle,
              name: pageTitle,
              widget: hidden,
              default: About Page,
            }
          - { label: Slug, name: slug, widget: hidden, default: "about" }
          - { label: title, name: title, widget: string }
          - { label: short description, name: shortDescription, widget: text }
          - { label: description, name: description, widget: text }
          - { label: Image, name: image, widget: image }
          - { label: team title, name: teamTitle, widget: string }
          - label: "services section"
            name: "servicesSection"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }

          - label: "Inline Banner"
            name: "inlineBanner"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }
              - { label: Background, name: background, widget: image }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }

      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: ContactPage,
            }
          - {
              label: PageTitle,
              name: pageTitle,
              widget: hidden,
              default: Contact Page,
            }
          - { label: Slug, name: slug, widget: hidden, default: "contact" }
          - { label: title, name: title, widget: string }
          - {
              label: contact Text title,
              name: contactTextTitle,
              widget: string,
            }
          - { label: text, name: text, widget: text }
          - { label: location title, name: locationTitle, widget: string }
          - { label: address, name: address, widget: string }
          - {
              label: opening hours title,
              name: openingHoursTitle,
              widget: string,
            }
          - {
              label: opening hours,
              name: openingHours,
              widget: markdown,
              buttons: { bulleted-list, bold, italic },
            }
          - {
              label: contact info title,
              name: contactInfoTitle,
              widget: string,
            }
          - {
              label: contact info,
              name: contactInfo,
              widget: markdown,
              buttons: { bulleted-list, numbered-list, bold, italic, link },
            }
      - file: "content/pages/services.md"
        label: "Services Page"
        name: "services-index"
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: servicesIndex,
            }
          - {
              label: PageTitle,
              name: pageTitle,
              widget: hidden,
              default: Services,
            }
          - { label: Slug, name: slug, widget: hidden, default: services }
          - { label: title, name: title, widget: string }
          - { label: short description, name: shortDescription, widget: text }
          - { label: description, name: description, widget: text }
          - { label: Image, name: image, widget: image }
          - label: "Inline Banner"
            name: "inlineBanner"
            widget: "object"
            fields:
              - { label: title, name: title, widget: string }
              - { label: description, name: description, widget: string }
              - { label: Background, name: background, widget: image }
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - label: "Link"
                    name: "link"
                    widget: "string"
                    default: ""
                    hint: "Copy past a url"
                  - { label: text, name: text, widget: string }

  - name: service
    label: Service
    editor:
      preview: true
    folder: content/services
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: SingleService,
        }
      - { label: Title, name: title, widget: string }
      - { label: short description, name: shortDescription, widget: text }
      - { label: description, name: description, widget: text }
      - { label: Image, name: image, widget: image }
      - label: "Info Section"
        name: "infoSection"
        widget: "object"
        fields:
          - { label: title, name: title, widget: string }
          - label: "Info Blocks"
            name: "infoblocks"
            widget: "list"
            required: false
            fields:
              - { label: "title", name: "title", widget: "string" }
              - { label: description, name: description, widget: text }
      - label: "Get in touch Section"
        name: "getInTouchSection"
        widget: "object"
        fields:
          - { label: title, name: title, widget: string }
          - { label: subtitle, name: subtitle, widget: string }
          - label: "Button 1"
            name: "button1"
            widget: "object"
            fields:
              - label: "Link"
                name: "link"
                widget: "string"
                default: ""
                hint: "Copy past a url"
              - { label: text, name: text, widget: string }
          - label: "Button 2"
            name: "button2"
            widget: "object"
            fields:
              - label: "Link"
                name: "link"
                widget: "string"
                default: ""
                hint: "Copy past a url"
              - { label: text, name: text, widget: string }

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Header Meta / Scripts,
              name: headerScripts,
              widget: text,
              required: false,
            }
